services:
  app-db:
    image: "postgres:12-alpine"
    container_name: app-db
    volumes:
      - app-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vezeeta
      - POSTGRES_USER=vezeeta
      - POSTGRES_PASSWORD=vezeeta

  app-backend:
    build: ./back
    container_name: app-backend
    environment:
      - DB_SERVER=app-db
      - POSTGRES_DB=vezeeta
      - POSTGRES_USER=vezeeta
      - POSTGRES_PASSWORD=vezeeta

  app-frontend:
    build: ./front
    container_name: app-frontend
    ports:
      - 4200:80
    links:
      - app-backend

volumes:
  app-data:
